name: medrpha_customer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# version: 1.0.0+1
#TODO: Update the version of app here
version: 1.0.1+26

environment:
  sdk: ">=2.16.2 <3.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  cached_network_image: ^3.2.1
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.2
  dio: ^5.1.0
  dotted_border: ^2.0.0+3
  downloads_path_provider_28: ^0.1.2
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  fluttertoast: ^8.0.9
  http: ^0.13.4
  image_picker: ^0.8.5+3
  launch_review: ^3.0.1
  mobx: ^2.0.7+4
  open_filex: ^4.3.2
  package_info_plus: ^1.4.2
  pay: ^1.0.11
  permission_handler: ^10.0.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  razorpay_flutter: ^1.3.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  speech_to_text: ^5.6.1
  sticky_headers: ^0.3.0+2

dev_dependencies:
  build_runner: ^2.1.11
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/playstore.png"
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: SFProText
    #   fonts:
    #     - asset: fonts/SFProText-Bold.otf
    #     - asset: fonts/SFProText-Medium.otf
    #     - asset: fonts/SFProText-Regular.otf
    # - family: Roboto
    #   fonts:
    #     - asset: fonts/Roboto-Black.ttf
    #     - asset: fonts/Roboto-Bold.ttf
    #     - asset: fonts/Roboto-Light.ttf
    #     - asset: fonts/Roboto-Medium.ttf
    #     - asset: fonts/Roboto-Regular.ttf
    #     - asset: fonts/Roboto-Thin.ttf
    # - family: Montserrat
    #   fonts:
    #     - asset: fonts/Montserrat-ExtraBold.ttf
    #     - asset: fonts/Montserrat-SemiBold.ttf
    #     - asset: fonts/Montserrat-Light.ttf
    #     - asset: fonts/Montserrat-Medium.ttf
    #     - asset: fonts/Montserrat-Regular.ttf
    #     - asset: fonts/Montserrat-Thin.ttf
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Thin.ttf
          weight: 300
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: fonts/Gilroy-Black.ttf
          weight: 900
        # - asset: fonts/Gilroy-UltraLight.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
