name: medrpha_customer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  cached_network_image: ^3.2.0
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  dropdown_search: ^3.0.1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.5
  flutter_slidable: ^1.3.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  mobx: ^2.0.7
  motion_tab_bar: ^0.1.5
  pin_input_text_field: ^4.1.2
  provider: ^6.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProText
      fonts:
        - asset: fonts/SFProText-Bold.otf
        - asset: fonts/SFProText-Medium.otf
        - asset: fonts/SFProText-Regular.otf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
